#!/bin/bash

#   file: setupfiles
#   type: Bash script

#   Copyright (C) 2016  fkol k4, "fkolyvas at gmail dot com"

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#   Set file pool & copy setup files to system
function copy_pool_to_system() {
    clear; echo
    echo "1. Copying extra files from pool to system. Please wait..."; sleep 3
    file_pool_folder="$HOME/fkol-k4.archlinux.extras/systemfiles-ubuntu"
    sudo cp -r $file_pool_folder/* /
}


#   Set permissions
function set_permissions() {
    clear; echo
    echo "2. Setting new file permissions. Please wait..."; sleep 3
    cd $HOME
    sudo chown -R $USER:$USER `ls -A`
    sudo chown -R $USER:$USER /usr/share/icons/fkol-k4
    sudo chown $USER:$USER /usr/local/bin/fkol-k4.*
    sudo chown -R $USER:$USER /usr/share/wallpapers/fkol-k4
}


#   Create links
function create_links() {
    clear; echo
    echo "3. Creating some needed symbolic links. Please wait..."; sleep 3
    cd $HOME
    ln -sf /usr/share/icons/fkol-k4 .icons
}


#   Run script
copy_pool_to_system
set_permissions
create_links
